app: sonostate
nodes: 1
tasks_per_node: 7
folder: /scratch/bxu/project/EchoJEPA/checkpoints/sonostate_pretrained_fp32
data:
  dataset_type: VideoDataset
  datasets:
  - /scratch/bxu/project/echonet/pretrain_annotations.csv
  datasets_weights:
  - 1.0
  batch_size: 64
  crop_size: 224
  patch_size: 16
  dataset_fpcs:
  - 16
  fps: 8
  tubelet_size: 2
  num_clips: 2
  num_workers: 8
  persistent_workers: true
  pin_mem: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.9
  - 1.1
  random_resize_scale:
  - 0.5
  - 1.0
  reprob: 0.0
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 8
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.7
  - 0.7
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: bfloat16
  load_checkpoint: false
  read_checkpoint: null
  save_every_freq: 25
  seed: 234
  use_sdpa: true
model:
  model_name: vit_large
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_mask_tokens: true
  num_mask_tokens: 10
  use_rope: true
  zero_init_mask_tokens: true
sonostate:
  state_dim: 256
  transition_hidden_dim: 512
  lambda_forecast: 0.1
optimization:
  force_load_pretrain: true
  anneal_ckpt: /scratch/bxu/project/EchoJEPA/checkpoints/pretrained/vitl.pt
  is_anneal: false
  ema: [0.998, 1.0]
  weight_decay: 0.04
  final_weight_decay: 0.04
  ipe_scale: 1.0
  start_lr: 1.0e-6
  lr: 3.0e-5
  final_lr: 1.0e-6
  warmup: 10
  epochs: 150
